### ISSUE TITLE
Document how to set up HTTPS 1st draft

### ISSUE THREAD

**Issue by sandbergja** [openbiblio/openbiblio_docs#2]

**Comment by flaplante** [comment]
Waiting anxiously to see what you place here. 

Or was this a gentle hint to share my own experience?

**Comment by sandbergja** [comment]
Either way!  I was looking to get my hands on the book you mentioned and try out the process myself, but also very happy if you want to add this documentation as well. :-)

**Comment by flaplante** [comment]
OK, I have the book right here. Need a break from javascript objects.
Let me get a first draft together.
